SELECT 
    CAST(AVG(LAT_N) AS DECIMAL(10,4)) AS MEDIAN
FROM (
    SELECT LAT_N,
        ROW_NUMBER() OVER (ORDER BY LAT_N) AS ROWASC,
        ROW_NUMBER() OVER (ORDER BY LAT_N DESC) AS ROWDESC
    FROM STATION
) AS RANKED
WHERE ROWASC = ROWDESC OR ROWASC + 1 = ROWDESC;
